# Generated by Django 5.0.7 on 2024-07-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Germany', 'Germany'), ('France', 'France'), ('Japan', 'Japan')], max_length=50, null=True)),
                ('state', models.CharField(blank=True, choices=[('Tamil Nadu', 'Tamil Nadu'), ('California', 'California'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat')], max_length=50, null=True)),
                ('city', models.CharField(blank=True, choices=[('Coimbatore', 'Coimbatore'), ('Bengaluru', 'Bengaluru'), ('Mumbai', 'Mumbai'), ('Jaipur', 'Jaipur'), ('Lucknow', 'Lucknow'), ('Hyderabad', 'Hyderabad')], max_length=50, null=True)),
            ],
        ),
    ]
