# Generated by Django 5.0.7 on 2024-07-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(max_length=10, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(choices=[('India', 'india'), ('Usa', 'usa'), ('Uk', 'uk'), ('Malesia', 'malesia'), ('Srilanka', 'srilanka')], max_length=20, null=True)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'andhra pradesh'), ('Tamilnadu', 'tamilnadu'), ('Odisha', 'odisha'), ('Telengana', 'telengana'), ('Himanchal Pradesh', 'himanchal pradesh')], max_length=20, null=True)),
                ('city', models.CharField(choices=[('Srikakulam', 'srikakulam'), ('Visakhapatnam', 'visakhapatnam'), ('Ichchapuram', 'ichchapuram'), ('Vijayawada', 'vijayawada'), ('Hyderabad', 'hyderabad')], max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
