# Generated by Django 5.0.7 on 2024-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAppOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='<br><b>Upload a profile photo</b>', null=True, upload_to='profile_pics/')),
                ('restaurant_name', models.CharField(max_length=100, unique=True)),
                ('restaurant_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=50)),
                ('restaurant_description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('social_media_links', models.JSONField(blank=True, help_text='Enter social media links as a JSON object', null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('operational_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('specialties', models.CharField(blank=True, help_text='E.g., Italian, Chinese, etc.', max_length=255, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(choices=[('Coimbatore', 'coimbatore'), ('Bengaluru', 'bengaluru'), ('Mumbai', 'mumbai'), ('Jaipur', 'jaipur'), ('Lucknow', 'lucknow'), ('Hyderabad', 'hyderabad')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(choices=[('India', 'india'), ('USA', 'SA'), ('UK', 'uK'), ('Canada', 'canada'), ('Australia', 'australia'), ('Germany', 'germany'), ('France', 'france'), ('Japan', 'japan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(choices=[('Tamil Nadu', 'tamil nadu'), ('California', 'california'), ('Andhra Pradesh', 'andhra pradesh'), ('Arunachal Pradesh', 'arunachal pradesh'), ('Assam', 'Assam'), ('Bihar', 'bihar'), ('Chhattisgarh', 'chhattisgarh'), ('Goa', 'goa'), ('Gujarat', 'gujarat')], max_length=20, null=True),
        ),
    ]
