# Generated by Django 5.0.7 on 2024-08-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_foodappowner_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodappowner',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='foodappowner',
            name='profile',
            field=models.ImageField(help_text='<br><b>Upload a profile photo</b>', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='foodappowner',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='foodappowner',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodappowner',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
