# Generated by Django 5.0.7 on 2024-08-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_foodappowner_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodappowner',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodappowner',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='foodappowner',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='foodappowner',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodappowner',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='foodappowner',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodappowner',
            name='profile',
            field=models.ImageField(help_text='<br><b>upload profile photo<b>', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='foodappowner',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
